/* generated by Atletik vX.Y.Z */
import { AtletikComponent, init, safe_not_equal } from "Atletik/internal";

const SOME_CONSTANT = 42;

function foo(bar) {
	console.log(bar);
}

function instance($$self, $$props, $$invalidate) {
	return [foo];
}

class Component extends AtletikComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, { foo: 0 });
	}

	get foo() {
		return foo;
	}
}

export default Component;
export { SOME_CONSTANT };