/* generated by Atletik vX.Y.Z */
import { create_ssr_component } from "Atletik/internal";

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<div>content</div>
<!-- comment -->
<div>more content</div>`;
});

export default Component;
