/* generated by Atletik vX.Y.Z */
import {
	AtletikComponent,
	create_component,
	destroy_component,
	init,
	mount_component,
	noop,
	safe_not_equal,
	transition_in,
	transition_out
} from "Atletik/internal";

import LazyLoad from './LazyLoad.Atletik';

function create_fragment(ctx) {
	let lazyload;
	let current;
	lazyload = new LazyLoad({ props: { load: func } });

	return {
		c() {
			create_component(lazyload.$$.fragment);
		},
		m(target, anchor) {
			mount_component(lazyload, target, anchor);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(lazyload.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(lazyload.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(lazyload, detaching);
		}
	};
}

const func = () => import('./Foo.Atletik');

class Component extends AtletikComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;