/* generated by Atletik vX.Y.Z */
import { AtletikComponent, init, safe_not_equal } from "Atletik/internal";

function instance($$self) {
	class A {
		p1;
		p2 = 1;
		#p3 = 2;

		#getP3() {
			return this.#p3;
		}
	}

	return [];
}

class Component extends AtletikComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, {});
	}
}

export default Component;
