/* generated by Atletik vX.Y.Z */
import {
	AtletikComponent,
	append,
	detach,
	init,
	insert,
	noop,
	safe_not_equal,
	set_svg_attributes,
	svg_element
} from "Atletik/internal";

function create_dynamic_element(ctx) {
	let Atletik_element1;
	let Atletik_element0;

	return {
		c() {
			Atletik_element1 = svg_element(/*tag*/ ctx[0].svg);
			Atletik_element0 = svg_element(/*tag*/ ctx[0].path);
			set_svg_attributes(Atletik_element0, { xmlns: "http://www.w3.org/2000/svg" });
			set_svg_attributes(Atletik_element1, { xmlns: "http://www.w3.org/2000/svg" });
		},
		m(target, anchor) {
			insert(target, Atletik_element1, anchor);
			append(Atletik_element1, Atletik_element0);
		},
		p: noop,
		d(detaching) {
			if (detaching) detach(Atletik_element1);
		}
	};
}

function create_fragment(ctx) {
	let Atletik_element = /*tag*/ ctx[0].svg && create_dynamic_element(ctx);

	return {
		c() {
			if (Atletik_element) Atletik_element.c();
		},
		m(target, anchor) {
			if (Atletik_element) Atletik_element.m(target, anchor);
		},
		p(ctx, [dirty]) {
			if (/*tag*/ ctx[0].svg) {
				Atletik_element.p(ctx, dirty);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (Atletik_element) Atletik_element.d(detaching);
		}
	};
}

function instance($$self) {
	const tag = { svg: 'svg', path: 'path' };
	return [tag];
}

class Component extends AtletikComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;