/* generated by Atletik vX.Y.Z */
import { AtletikComponent, init, safe_not_equal } from "Atletik/internal";

function instance($$self) {
	const a = 1 + 2;
	return [];
}

class Component extends AtletikComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, {});
	}
}

export default Component;